# -*- coding: utf-8 -*-
"""project 1 code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Kzo32EH_lDU18th9kT2j--bPeosGCB4

Project 1, Question 3
"""

# P is the principal of the loan
P=100
# T is the lifespan of the loan
T=30
#r is the anual rate
r=0.1
# m is the number of payments per year
m=12

#formula for fixed payment (C)
P *(1-(1+(r/m))**(-1))/((1+r/m)**(-1)-(1+r/m)**(-T*m-1))

def my_loan_calculator (principal,life_span,payments_per_year,rate):

  #compute the discount factor for one period
  discount_factor= (1+rate/payments_per_year)**(-1)

  #compute payment per period
  amount_per_payment= principal*(1-discount_factor)/(discount_factor-discount_factor**(life_span*payments_per_year +1))

  return amount_per_payment

#calculate each payment using given values
my_loan_calculator(100,20,12,0.05)

# Loan Schedule
def loan_schedule(principal,life_span,payments_per_year,rate):

  #loan schedule calculated using loan calculator
  payment_amount=my_loan_calculator(principal,life_span,payments_per_year,rate)

  #start with initial loan balance
  balance=principal

  #loop for all payments (here 360)
  for i in range(life_span*payments_per_year):

    #calculate interest owed this payment
    accrued_interest=balance*rate/payments_per_year

    #calculate principal portion owed this payment
    principal_paid = payment_amount - accrued_interest

    print(f"At time {i+1}, the balance before payment is {balance}, the principal\
    paid is {principal_paid}, the accrued interest is {accrued_interest}")

    #update balance
    balance=balance-(payment_amount-accrued_interest)

  print(f"At time {i+1}, the final balance is {balance}")

  return balance

loan_schedule(100,10,2,0.05)